%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Documents/GitHub/AGRO-SOFC/code/Model&Optimization/data/expdata/reformer-data-10000-samples-Ver01 - reformer-data-10000-samples-Ver01.csv
%
% Auto-generated by MATLAB on 27-Nov-2020 16:37:28

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 42);

% Specify range and delimiter
opts.DataLines = [5, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "ratios", "VarName21", "VarName22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"];
opts.SelectedVariableNames = ["ratios", "VarName21", "VarName22"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "ratios", "VarName21", "VarName22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "ratios", "VarName21", "VarName22", "Var23", "Var24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"], "EmptyFieldRule", "auto");

% Import the data
reformerdata10000samplesVer01reformerdata10000samplesVer01 = ...
readtable("/Users/djoroya/Documents/GitHub/AGRO-SOFC/code/Model&Optimization/data/expdata/reformer-data-10000-samples-Ver01.csv", opts);


%% Clear temporary variables

inputs  = reformerdata10000samplesVer01reformerdata10000samplesVer01;
inputs.Properties.VariableNames = {'RatioSteamC','RatioOC','RatioHC'};


%%%
%%%

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Documents/GitHub/AGRO-SOFC/code/Model&Optimization/data/expdata/reformer-data-10000-samples-Ver01 - reformer-data-10000-samples-Ver01.csv
%
% Auto-generated by MATLAB on 27-Nov-2020 16:43:01

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 42);

% Specify range and delimiter
opts.DataLines = [5, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "VarName24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"];
opts.SelectedVariableNames = "VarName24";
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "VarName24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "VarName24", "Var25", "Var26", "Var27", "Var28", "Var29", "Var30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"], "EmptyFieldRule", "auto");

% Import the data
reformerdata10000samplesVer01reformerdata10000samplesVer01 = ...
readtable("/Users/djoroya/Documents/GitHub/AGRO-SOFC/code/Model&Optimization/data/expdata/reformer-data-10000-samples-Ver01.csv", opts);


%% Clear temporary variables
clear opts

%%
reformerdata10000samplesVer01reformerdata10000samplesVer01.Properties.VariableNames = {'Temperature'};

inputs = horzcat(reformerdata10000samplesVer01reformerdata10000samplesVer01,inputs);

inputs.Temperature = double(replace(inputs.Temperature,',','.'));
inputs.RatioSteamC = double(replace(inputs.RatioSteamC,',','.'));
inputs.RatioHC = double(replace(inputs.RatioHC,',','.'));
inputs.RatioOC = double(replace(inputs.RatioOC,',','.'));

%%

%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/djoroya/Documents/GitHub/AGRO-SOFC/code/Model&Optimization/data/expdata/reformer-data-10000-samples-Ver01 - reformer-data-10000-samples-Ver01.csv
%
% Auto-generated by MATLAB on 27-Nov-2020 16:58:25

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 42);

% Specify range and delimiter
opts.DataLines = [5, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "VarName28", "VarName29", "VarName30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"];
opts.SelectedVariableNames = ["VarName28", "VarName29", "VarName30"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "VarName28", "VarName29", "VarName30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "Var2", "Var3", "Var4", "Var5", "Var6", "Var7", "Var8", "Var9", "Var10", "Var11", "Var12", "Var13", "Var14", "Var15", "Var16", "Var17", "Var18", "Var19", "Var20", "Var21", "Var22", "Var23", "Var24", "Var25", "Var26", "Var27", "VarName28", "VarName29", "VarName30", "Var31", "Var32", "Var33", "Var34", "Var35", "Var36", "Var37", "Var38", "Var39", "Var40", "Var41", "Var42"], "EmptyFieldRule", "auto");

% Import the data
reformerdata10000samplesVer01reformerdata10000samplesVer01 = ...
readtable("/Users/djoroya/Documents/GitHub/AGRO-SOFC/code/Model&Optimization/data/expdata/reformer-data-10000-samples-Ver01.csv", opts);


%% Clear temporary variables
clear opts

outputs = reformerdata10000samplesVer01reformerdata10000samplesVer01;
outputs.Properties.VariableNames = {'CO','CO2','H2'};
outputs.CO = double(replace(outputs.CO,',','.'));
outputs.H2 = double(replace(outputs.H2,',','.'));
outputs.CO2 = [];

%%
save('data/expdata/reformer-data','inputs','outputs')